# Generated by Django 2.2.28 on 2023-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test_rr'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ddbbb',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
