# Generated by Django 2.2.28 on 2023-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_test_ddbbb'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttt', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='dfassasdffasd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='dfs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tTddd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
